# Generated by Django 3.1.2 on 2020-10-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201012_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontoturistico',
            options={'verbose_name_plural': 'Pontos Turisticos'},
        ),
    ]
