# Generated by Django 3.1.2 on 2020-10-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name_plural': 'Comentários'},
        ),
    ]
