# Generated by Django 3.1.2 on 2020-10-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_auto_20201012_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name_plural': 'Atrações'},
        ),
    ]
