# Generated by Django 3.1.2 on 2020-10-16 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0005_atracao_observacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atracao',
            name='observacoes',
        ),
    ]
