# Generated by Django 3.1.2 on 2020-10-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0006_remove_atracao_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='observacoes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
